# Generated by Django 5.2.12 on 2026-03-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='logo',
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
