# Generated by Django 5.2.12 on 2026-03-11 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_remove_vendor_logo_vendor_banner_vendor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
